name: py36
channels:
  - conda-forge
dependencies:
  - adaptive=0.7.*
  - dask=1.0.*
  - dask-jobqueue=0.4.*
  - fenics=2017.2.*
  - freecad=0.18*
  - future=0.17.*
  - holoviews=1.10.*
  - hpc05=v1.30
  - h5py=2.8.*
  - jupyter=1.0.*
  - kwant=1.3.*
  - libgfortran-ng=7.2.*
  - matplotlib=2.2.*
  - mkl=2018.0.*
  - mkl-service=1.1.*
  - mpi4py=3.0.*
  - numpy=1.13.*
  - numpy-stl=2.8.*
  - petsc=3.8.*
  - pytest=4.0.*
  - python=3.6
  - scipy=1.1.*
  - shapely=1.6.*
  - sphinx=1.8.*
  - sympy=1.3.*
  - tqdm=4.28.*
