# This files lists the minimum set of packages that we need for QMS/QMT
# Version locking and explicit dependencies are kept to a minimum. If any they are explained,
# and could potentially be removed in the future
# This file is kept around so that if we want to upgrade version numbers, we can conda build
# on this. If not please use environment_full_[platform].yml, which is much less likely to give you issues
# due to packages versioning
name: py37
channels:
  - conda-forge
dependencies:
  - adaptive
  - black
  - dask
  - dask-jobqueue
  - deepdish
  - descartes
  - fenics
  - freecad
  - future
  - holoviews
  - hpc05
  - h5py
  - jupyter
  - jupyter_contrib_nbextensions
  - kwant
  - matplotlib
  - mkl
  - mkl-service
  - mpi4py
  - nb_conda
  - numpy
  - numpy-stl
  - petsc
  - pre_commit
  - pylint
  - pytest
  - pytest-cov
  - pytest-datadir
  - pytest-xdist
  - rope
  - scipy
  - shapely
  - sphinx
  - sympy
  - tqdm
